changelog:
  categories:
    - title: 💥 破坏性
      labels:
        - breaking
    - title: ✨ 新特性
      labels:
        - enhancement
    - title: 🐛 错误修复
      labels:
        - bug
    - title: 💫 杂项
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
