ci:
  autofix_commit_msg: "🚨 通过预提交挂钩自动修复"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: monthly
  autoupdate_commit_msg: "⬆️ 自动更新预提交挂钩"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit]
      - id: ruff-format
        stages: [commit]
