name: Pyright Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - kirami/**
      - pyproject.toml

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.6
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Project
        run: uv sync --frozen

      - name: Use Virtualenv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
