name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - kirami/**
      - pyproject.toml

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.0.282
